import type { CollectionConfig } from 'payload'
import { lexicalEditor } from '@payloadcms/richtext-lexical'

export const AgendaItems: CollectionConfig = {
  slug: 'agenda-items',
  access: {
    read: () => true,
  },
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['number', 'title', 'status'],
  },
  fields: [
    {
      name: 'number',
      type: 'number',
      required: true,
      min: 1,
      max: 12,
      admin: { description: 'Agenda item number (1–12)' },
    },
    {
      name: 'title',
      type: 'text',
      required: true,
      localized: true,
    },
    {
      name: 'summary',
      type: 'textarea',
      required: true,
      localized: true,
      admin: { description: '1-2 sentence plain language summary' },
    },
    {
      name: 'fullContent',
      type: 'richText',
      localized: true,
      editor: lexicalEditor({}),
    },
    {
      name: 'plainLanguageSummaryMs',
      type: 'textarea',
      admin: {
        description: 'BM Mudah level explanation (auto-generated by AI, reviewed by Amir)',
      },
    },
    {
      name: 'plainLanguageSummaryEn',
      type: 'textarea',
      admin: { description: 'Plain English explanation' },
    },
    {
      name: 'icon',
      type: 'text',
      admin: { description: 'Emoji or icon identifier for this agenda item' },
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'status',
      type: 'select',
      options: ['draft', 'published'],
      defaultValue: 'draft',
    },
  ],
}
